import "./scss/main.scss";
import "./js/numbercategoryselector.js";
import "./components/dropdownGuest/numbercategoryselectorGuest.js";
import "./components/dropdownGuest2/numbercategoryselectorGuest2.js";
import "./components/cardSliderRoom/jquery.flexslider.js";
import "./components/cardSliderRoom/flexSlider.js";
import "./components/rangeSlider/rangeSlider.js";
import "./favicons/favicons.js";
import "./js/datepicker.min.js";
window.$ = jQuery;
window.jQuery = jQuery;
